background {
    monitor =
    path = $HOME/.local/share/archonic/wallpapers/current.jpg
    blur_passes = 2
    blur_size = 6
}

input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_center = true
    outer_color = rgb(cba6f7)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fail_color = rgb(f38ba8)
    placeholder_text = <i>Passwort</i>
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] $(date +"%H:%M")
    color = rgb(cdd6f4)
    font_size = 72
    position = 0, 80
    halign = center
    valign = center
}
