source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/autostart.conf

input {
    kb_layout = de
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
