general {
    col.active_border = rgba(88c0d0ee)
    col.inactive_border = rgba(3b4252aa)
}

decoration {
    rounding = 6
    blur {
        enabled = true
        size = 4
        passes = 2
    }
}

animations { enabled = true }
