# Wird via Symlink zu ~/.bashrc
[[ $- != *i* ]] && return

export EDITOR=nvim
export PATH="$HOME/.local/bin:$PATH"

alias ls='eza --group-directories-first'
alias ll='eza -l --git'
alias cat='bat --paging=never'

command -v zoxide >/dev/null && eval "$(zoxide init bash)"
